import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import {
  createDefaultPolicyConfig,
  DEFAULT_CONFIG_PATH,
  renderDefaultPolicyConfig,
} from '../../src/config/default-config';
import { loadConfig } from '../../src/config/load-config';

describe('loadConfig', () => {
  const originalCwd = process.cwd();
  const originalRunnerTemp = process.env['RUNNER_TEMP'];

  afterEach(async () => {
    process.chdir(originalCwd);
    if (originalRunnerTemp === undefined) {
      delete process.env['RUNNER_TEMP'];
    } else {
      process.env['RUNNER_TEMP'] = originalRunnerTemp;
    }
  });

  it('fails with onboarding instructions when config is missing', async () => {
    const workspace = await fs.mkdtemp(
      path.join(os.tmpdir(), 'pull-request-policy-workspace-'),
    );
    process.chdir(workspace);
    await expect(loadConfig()).rejects.toThrow(
      new RegExp(`No policy configuration found at ${DEFAULT_CONFIG_PATH}`),
    );
  });
});

describe('default policy configuration', () => {
  it('creates the two advisory policies with their intended predicates', () => {
    expect(createDefaultPolicyConfig()).toEqual({
      policies: [
        expect.objectContaining({
          id: 'workflow-change-needs-runbook',
          severity: 'warn',
          when: { changed: ['.github/workflows/**'] },
          require: {
            any: [
              { changed: ['docs/runbooks/**'] },
              { body: ['runbook', 'rollback'] },
            ],
          },
        }),
        expect.objectContaining({
          id: 'api-change-needs-release-note',
          severity: 'warn',
          when: { changed: ['api/public/**'] },
          require: {
            any: [
              { changed: ['CHANGELOG.md'] },
              { has_label: ['release-note-exempt'] },
            ],
          },
        }),
      ],
    });
  });

  it('renders a valid, actionable fallback configuration', () => {
    const rendered = renderDefaultPolicyConfig();

    expect(rendered).toContain('# Generated by pull-request-policy');
    expect(rendered).toContain('severity: warn');
    expect(rendered).toContain('".github/workflows/**"');
    expect(rendered).toContain('"api/public/**"');
    expect(rendered.endsWith('\n')).toBe(true);
  });
});
